Multi-read supported chardev.c without race condition of offset.
sysprog21/lkmpg pull request #110
Opened 2021-09-21 11:07 UTC by YLowy

2021-09-21 12:31 UTC, jserv commented on examples/chardev.c
> +}list_ele_t;
Run `clang-format -i chardev.c` in directory `examples`.

2021-09-21 12:31 UTC, jserv requested changes
Follow Linux kernel coding style and avoid using camelCase such as `currentOffset`.

2021-09-22 10:06 UTC, linD026 commented
This improvement with the multi-read is unnecessary because the read operation of the `struct file` already being atomic since Linux v3.14.
You can see more [here](https://github.com/sysprog21/lkmpg/pull/108#issuecomment-923965811).
Ps. Apologize for the previously misleading information that I talked about in the private messages.

2021-09-22 11:23 UTC, jserv commented
Close as per @linD026 suggested.

2021-09-22 11:23 UTC, closed without merging