Provide a tasklet-free example
sysprog21/lkmpg pull request #116
Opened 2021-09-25 03:54 UTC by jserv

It is possible that in future tasklets may be replaced by threaded irqs.

2021-09-25 10:17 UTC, linD026 requested changes

2021-09-25 10:17 UTC, linD026 commented on lkmpg.tex
> +It is expected that at some unspecified point in the future tasklets may eventually be deprecated, to be replaced by \textit{threaded irqs} instead.
In 2020, the removal of the tasklet API also has been discussed.
See https://lwn.net/Articles/830964/.

2021-09-25 10:17 UTC, linD026 commented on lkmpg.tex
> +It is expected that at some unspecified point in the future tasklets may eventually be deprecated, to be replaced by \textit{threaded irqs} instead.
Also, the patch of tasklets in 2020 has the same improvement as the `timer_setup`. In other words, the CET needs to be mention too.
See:
* https://github.com/torvalds/linux/commit/12cc923f1ccc1df467e046b02a72c2b3b321b6a2
* https://lwn.net/ml/kernel-hardening/20200716030847.1564131-1-keescook@chromium.org/

2024-04-19 16:28 UTC, 0xff07 commented
I sent a pull request to the `threaded-irq` branch.

2024-04-20 01:49 UTC, jserv commented
Close in favor of #255

2024-04-20 01:49 UTC, closed without merging