Add the explanation about `make` in section 4.1
sysprog21/lkmpg pull request #132
Opened 2021-11-26 01:24 UTC by mengxinayan

Add the explanation of the difference between `make` and `sudo make` by an example in section 4.1.

2021-11-26 01:33 UTC, jserv commented
Quoting the GNU Make Manual:
> `CURDIR`
> Set to the absolute pathname of the current working directory.
> 
> For your convenience, when GNU make starts (after it has processed any -C options) it sets the variable CURDIR to the pathname of the current working directory. This value is never touched by make again: in particular note that if you include files from other directories the value of CURDIR does not change. The value has the same precedence it would have if it were set in the makefile (by default, an environment variable CURDIR will not override this value). Note that setting this variable has no impact on the operation of make (it does not cause make to change its working directory, for example).

`CURDIR` is guaranteed to work in Make in `PWD` might be inherited from the shell, the former should be preferred.

2021-11-27 03:20 UTC, linD026 requested changes
Looks good.
Now, please add the `CURDIR` part mentioned by jesrv.
Thanks.

2021-11-30 02:47 UTC, mengxinayan commented
Hi @jserv @linD026 

Thanks. I want to replace all `PWD` with `CURDIR` in the book, and explain the situation mentioned above when using `PWD`.  Is it a good idea?

2021-11-30 03:00 UTC, linD026 commented
> Hi @jserv @linD026
> 
> Thanks. I want to replace all `PWD` with `CURDIR` in the book, and explain the situation mentioned above when using `PWD`. Is it a good idea?

I prefer to add the following statement which is from `example/Makefile` instead of replacing the `PWD` with `CURDIR`.
```make
PWD := $(CURDIR)
```

2021-11-30 12:28 UTC, mengxinayan commented
Hi @linD026 

Thanks for your suggestion. I will revise it by following your advice.

2021-11-30 23:49 UTC, jserv commented on lkmpg.tex
> +If there is no \verb|PWD := $(CURDIR)| statement in Makefile, note that using \verb|sudo make| might not compile. Because the \verb|sudo| will fork the process. According to the Process Model section
Add a hyperlink to `sudo` manual.

2021-12-01 02:57 UTC, mengxinayan commented on lkmpg.tex
> +If there is no \verb|PWD := $(CURDIR)| statement in Makefile, note that using \verb|sudo make| might not compile. Because the \verb|sudo| will fork the process. According to the Process Model section
Thanks, I have added it.

2021-12-01 13:43 UTC, closed without merging

2021-12-01 13:48 UTC, jserv commented
@mengxinayan, I wonder the reason and/or motivation why you close this pull request. I didn't find anything wrong.

2021-12-01 13:49 UTC, mengxinayan commented on lkmpg.tex
> +Now have a look at {drivers/char/Makefile} for a real world example.
Sorry, this is an accidental error modification by me :(

2021-12-01 13:53 UTC, mengxinayan commented
Hi @jserv @linD026 

Thanks for your suggestions. I open a new PR #133  to integrate all modifications, making it simply.

2021-12-01 13:57 UTC, mengxinayan commented
> @mengxinayan, I wonder the reason and/or motivation why you close this pull request. I didn't find anything wrong.

I just want to make all modifications simply. Maybe deleting it is not a good idea ? I have no idea about this.