Improve readability
sysprog21/lkmpg pull request #96
Opened 2021-09-08 01:45 UTC by Kellegram

Related issue #82 

This new foreground + background color maintains the minimum of 7:1 contrast ratio as specified by WCAG (this has 7.36:1) and is the same colors firefox reading mode uses when choosing the sepia theme. 

Fonts are too small by default, using responsive units (em) let's me increase them, I am unsure where or if there is font-size specified for parent anywhere but it seems to have been manually decreased.

Increased max-width slightly to adjust for new size and more standard line-height, so the doc doesn't feel significantly longer, still maintains good eye travel.

2021-09-08 01:46 UTC, Kellegram commented
Let me know if I edited the cfg correctly. Code syntax highlight could use a change if this were to be used. It, would need to have slightly darker colors, it's already close to having good contrast ratios for the most part.

2021-09-08 01:53 UTC, Kellegram commented
Also consider using better font, like Manrope. Manrope has a variable weight version and from my experience, people with accessibility issues don't struggle with it. Variable weight means you can use semi-bold which is great, it has pleasant shape and scales really well. (https://manropefont.com/)

2021-09-08 03:34 UTC, jserv commented
Manrope is an open-source modern sans-serif font family. These fonts are licensed under the Open Font License. It is great to LKMPG development.

2021-09-08 03:47 UTC, fennecJ requested changes
The output looks promising to me after fix those minor problems.

2021-09-08 03:47 UTC, fennecJ commented on html.cfg
> +    background-color: #F4ECD8;
Add '\\' before character '#', otherwise `make4ht` will see it as escape character and raise error.

2021-09-08 03:47 UTC, fennecJ commented on html.cfg
> +    color: #5B464B;
Ditto, add '\\' before character '#'.

2021-09-08 03:47 UTC, fennecJ commented on html.cfg
> +color: #0060DF;
Ditto, add '\\' before character '#'.

2021-09-08 19:32 UTC, Kellegram commented
Fixed it. if there is anything else that you want me to fix or change let me know. I find this version readable but it's good to have second opinion, perhaps you noticed something that doesn't look the way it was intended?

2021-09-09 03:17 UTC, fennecJ approved these changes
Looks good to me.

2021-09-09 03:20 UTC, merged

2021-09-09 08:26 UTC, jserv commented
Thank @Kellegram for contributing!